version: "3.8"

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: Npm_app
    network_mode: Serveur
    dns: 1.1.1.1
    restart: always
    ports:
      # Public HTTP Port:
      - '$NPM_HTTP_PORT:80'
      # Public HTTPS Port:
      - '$NPM_HTTPS_PORT:443'
      # Admin Web Port:
      - '$NPM_Admin_PORT:81'
    environment:
      DB_MYSQL_HOST: $NPM_MYSQL_HOSTNAME
      DB_MYSQL_PORT: $NPM_MYSQL_DB_PORT
      DB_MYSQL_USER: $NPM_MYSQL_USERNAME
      DB_MYSQL_PASSWORD: $NPM_MYSQL_PASSWORD
      DB_MYSQL_NAME: $NPM_MYSQL_DB_NAME
      DISABLE_IPV6: 'true'
    volumes:
      - /home/docker/Npm/data:/data
      - /home/docker/Npm/letsencrypt:/etc/letsencrypt
      - /home/docker/Npm/var/logs:/var/log
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: Npm_db
    network_mode: Serveur
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $NPM_MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $NPM_MYSQL_DB_NAME
      MYSQL_USER: $NPM_MYSQL_USERNAME
      MYSQL_PASSWORD: $NPM_MYSQL_PASSWORD
    volumes:
      - ./data/mysql:/var/lib/mysql
