version: '3.8'

services:
  nextcloud_db:
    image: mariadb:latest
    container_name: nextcloud_db
    network_mode: Serveur
    restart: always
    volumes:
      - /home/docker/nextcloud/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $NEXTCLOUD_MYSQL_ROOT_PASSWORD  # Mot de passe de l'utilisateur root de mariadb
      MYSQL_DATABASE: $NEXTCLOUD_MYSQL_DATABASE  # Nom de la base de données à créer à l'initialisation du conteneur
      MYSQL_USER: $NEXTCLOUD_MYSQL_USER  # Nom de l'utilisateur de la base de données créée
      MYSQL_PASSWORD: $NEXTCLOUD_MYSQL_PASSWORD  # Mot de passe de l'utilisateur créé

  nextcloud_app:
    image: nextcloud:latest
    container_name: nextcloud_app
    network_mode: Serveur
    restart: always
    ports:
      - $NEXTCLOUD_PORT:80
    links:
      - nextcloud_db
    volumes:
      - /home/docker/nextcloud/html:/var/www/html
      - /home/docker/nextcloud/data:/var/www/html/data
    environment:
      MYSQL_HOST: $NEXTCLOUD_MYSQL_HOSTNAME  # Nom du conteneur de la base de données
      MYSQL_DATABASE: $NEXTCLOUD_MYSQL_DATABASE  # Nom de la base de données
      MYSQL_USER: $NEXTCLOUD_MYSQL_USER  # Nom de l'utilisateur de la base de données
      MYSQL_PASSWORD: $NEXTCLOUD_MYSQL_PASSWORD  # Mot de passe de l'utilisateur de la base de données
