version: "3.3"
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: Transmission
    network_mode: Serveur
    hostname: "transmission"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    environment:
      - TZ=Europe/Paris
      OPENVPN_PROVIDER: $OPENVPN_PROVIDER
      OPENVPN_CONFIG: $OPENVPN_CONFIG
      OVPN_USERNAME: $VPN_USERNAME
      OVPN_PASSWORD: $VPN_PASSWORD
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_RPC_WHITELIST_ENABLED=true
      - TRANSMISSION_RPC_WHITELIST="127.0.0.1,192.168.1.*,172.18.0.*"
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      TRANSMISSION_RPC_USERNAME: $TRANSMISSION_RPC_USERNAME
      TRANSMISSION_RPC_PASSWORD: $TRANSMISSION_RPC_PASSWORD
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT="1.00"
      - DOWNLOAD_QUEUE_ENABLED=true
      - DOWNLOAD_QUEUE_SIZE="20"
      - QUEUE_STALLED_ENABLED=true
      - QUEUE_STALLED_MINUTES="30"
      - SEED_QUEUE_ENABLED=true
      - SEED_QUEUE_SIZE="10"
    volumes:
      - /home/downloads:/data

    ports:
      - 9091:9091

    restart: always
