version: '3'
services:
  netdata:
    image: netdata/netdata:latest
    network_mode: Serveur
    hostname: "netdata"
    container_name: Netdata
    environment:
      - TZ=Europe/Paris
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

    restart: unless-stopped
